# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operationsystem: 'ubuntu-latest'
#     mac:
#       operationsystem: 'macos-latest'
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo 'Do the build'
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo 'start Dev Deploy'
  - deployment: DevDeployJob
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deploy to Dev
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo 'start QA Deploy'
  - deployment: QADeployJob
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deploy to QA
